<a href="https://colab.research.google.com/github/TheMacaroni/Trashed/blob/main/PRO_C126_Student_Boilerplate(pt).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problema de Aprendizado por Reforço (RL) a Resolver:

A **máquina/robô** precisa encontrar uma maneira de alcançar o **Objetivo** (Sala Número 5). A máquina iniciará aleatoriamente de qualquer sala.

<img src="https://s3-whjr-curriculum-uploads.whjr.online/8c97608b-f644-411b-a619-bf2b5bb5cc84.PNG" width= 400>



## Componentes do RL:

* Ambiente 

<img src="https://s3-whjr-curriculum-uploads.whjr.online/af5a1d77-041a-4bba-be4e-ca26aea97771.png" width= 300>

* Agente

<img src="https://s3-whjr-curriculum-uploads.whjr.online/fda2e793-0302-420c-981b-dbf32ecb1d12.png" width= 200> 

* Estados

> O agente/máquina pode estar em qualquer uma das 6 salas do salão (5 salas + 1 sala do objetivo). Portanto, há **6 estados possíveis**.


> <img src="https://s3-whjr-curriculum-uploads.whjr.online/8373d662-7b47-4bad-9504-3ecf790e2644.PNG" width= 75> 


* Ações

> O agente/máquina pode decidir se mover para qualquer uma das 6 salas do salão (5 salas + 1 sala do objetivo). Portanto, também há **6 ações possíveis**.


> <img src="https://s3-whjr-curriculum-uploads.whjr.online/197a63c6-99ac-4d46-9026-bbc6321013b1.PNG" width= 300> 




* Recompensas

> **Recompensas possíveis: -1, 0, 100**

> <img src="https://s3-whjr-curriculum-uploads.whjr.online/d35adac2-7aef-42b3-a6f7-8c5b87393201.PNG" width= 300> 




* **Não pode se mover**: Se não houver um caminho direto de uma sala para outra, a recompensa será -1.

* **Pode se mover**: Se a máquina puder se mover da sala atual (estado) para a próxima sala (ação), a recompensa será 0.

* **Objetivo**: Se a máquina atingir o objetivo, então a recompensa será 100.


## Importe os Módulos

In [36]:
import numpy as np
import random

## Matriz de Recompensas

> Clique no link da [Matriz de Recompensas](https://s3-whjr-prod-cocos-applet.whjr.online/Coding/other/simple-q/index.html?play-mode=2&appletConfig.i18n.currentLanguage=BR&appletConfig.i18n.enabled=true) para entender a alocação das recompensas.

> <img src="https://s3-whjr-curriculum-uploads.whjr.online/6572d83b-7d56-40bc-8ca4-733ba220d7c2.PNG" width= 400>


* **Não pode se mover**: Se não houver um caminho direto de uma sala para outra, a recompensa será -1.

* **Pode se mover**: Se a máquina puder se mover da sala atual (estado) para a próxima sala (ação), a recompensa será 0.

* **Objetivo**: Se a máquina atingir o objetivo, então a recompensa será 100.

> <img src="https://s3-whjr-curriculum-uploads.whjr.online/31a41959-623e-4275-9bba-3fca21015f6d.PNG" width= 400>



In [37]:
rewards = np.array([
    [-1, -1, -1, -1,  0,  -1],
    [-1, -1, -1,  0, -1, 100],
    [-1, -1, -1 , 0 ,-1 , -1],
    [-1,  0,  0 ,-1  ,-1 , -1],
    [0, -1, -1 , -1 ,-1 ,100],
    [-1, -1, -1, -1,  0, 100] 
])

## Estado Inicial

In [2]:
def set_initial_state():
    return np.random.randint(0, 6)

## Obtenha a Ação

In [3]:
def get_action(current_state, reward_matrix):
    available_action = []
    print("reward_matrix","\n",reward_matrix)    
    for action in enumerate(reward_matrix[current_state]):     
        if action[1]!= -1:            
            available_action.append(action[0]) 
    choose_action = random.choice(available_action)
    print("Estado Atual",current_state)
    print("A escolha aleatória da ação de",available_action,"é", choose_action)          
    return choose_action

##Matriz Q
O **Aprendizado Q** é um algoritmo de aprendizado por reforço. Dado o estado atual, ele ajuda a encontrar a melhor ação a ser tomada pelo agente. No Aprendizado Q, o Q significa Qualidade. A qualidade representa quanto a ação é útil para obter uma recompensa.
Para realizar o Aprendizado Q, usamos a **Matriz-Q**. Ela também possui a forma de estados como linhas e ações como colunas. Inicialmente, todos os elementos da matriz Q estão zerados.


In [38]:
q_matrix = np.zeros([6,6])
print(q_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Tome uma Ação

In [5]:
def take_action(current_state, reward_matrix, gamma):
    
    action = get_action(current_state, reward_matrix)
    
     #Estado, ação e recompensa atuais
    current_sa_reward = reward_matrix[current_state, action]

    #Novos estado, ação e recompensa
    q_sa_value = max(q_matrix[action,])
  
    #Estado Q atual
    q_current_state = current_sa_reward + (gamma * q_sa_value)

    #Atualize a matriz Q
    q_matrix[current_state,action] = q_current_state
    
    print("Matriz Q ","\n", q_matrix)

    new_state = action
    
    print("********************************************************************")
    
    if new_state == 5:
        print("Objetivo Atingido!")
    else: 
        print(f"Estado Anterior:{current_state} Novo Estado: {new_state}")
        
    return new_state

## Treinar o Modelo RL: Matriz Q
O objetivo é fazer com que o agente explore diferentes estados e alcance o objetivo; as recompensas são atualizadas após cada tentativa.

O agente conclui um **episódio** quando começa do estado inicial e atinge o objetivo.

Para cada ação, a matriz Q é atualizada. Isso atuará como o ambiente treinado para o agente. Usando a matriz Q atualizada, o agente pode procurar a recompensa máxima e encontrar o caminho ideal para qualquer estado.

Consulte o link abaixo para verificar como os episódios são executados e a matriz Q é atualizada.

[Execute Diversos Episódios](https://s3-whjr-prod-cocos-applet.whjr.online/Coding/other/simple-q/index.html?play-mode=0&appletConfig.i18n.currentLanguage=BR&appletConfig.i18n.enabled=true)


In [19]:
def run_episode(initial_state,reward_matrix, gamma): 

    new_state =  take_action(initial_state, reward_matrix, gamma)

     # ADICIONE O CÓDIGO AQUI ##
    while True:
      if new_state == 5:
        break
      else:
        new_state = take_action(new_state, reward_matrix, gamma)

In [32]:
def train(episodes, reward_matrix, gamma):
    print("Treinando...")
    
    for episode in range(episodes):
         print("episódio inicial:", episode)
         initial_state = set_initial_state()
         print('episódio gerado aleatoriamente:', initial_state) 
         if initial_state != 5:
          run_episode(initial_state, reward_matrix, gamma)
         print("episódio final:", episode)

    print("トレーニング完了! (TRAINING COMPLETE!)")
  
    return q_matrix


In [39]:
gamma = 0.8

# Obtenha a tabela Q
q_table = train(20, rewards, gamma)

print("Tabela Q Final: ", q_table)

Treinando...
episódio inicial: 0
episódio gerado aleatoriamente: 1
reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Estado Atual 1
A escolha aleatória da ação de [3, 5] é 3
Matriz Q  
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
********************************************************************
Estado Anterior:1 Novo Estado: 3
reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Estado Atual 3
A escolha aleatória da ação de [1, 2] é 1
Matriz Q  
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
********************************************************************
Estado Anter

## Melhor Caminho para o Objetivo

Observando a q_table, descobrimos que as recompensas são calculadas para diferentes estados e ações. Para um determinado estado, as recompensas máximas são dadas à ação que deve ser tomada para encontrar o caminho ideal para atingir o objetivo.

In [ ]:
def optimal_path(q_table):
    path=[]
     # ADICIONE O CÓDIGO AQUI ##

In [ ]:
Q_optimal_path, max_reward  = optimal_path(q_table)
print(Q_optimal_path, max_reward)

TypeError: ignored